package com.zhr.activerecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

    // User中定义的 public static final User dao对象是全局共享的，只能用于数据库查询，
    // 不能用于数据承载对象。数据承载需要使用new User().set(…)来实现。
    public static final User dao = new User().dao();
}
